
logging:
  level:
    root: DEBUG

server:
  port: 8080

spring:
  application:
    name: gateway
  r2dbc:
    url: r2dbc:mariadb://localhost:3306
    name: gateway-database
    username: gateway
    password: gateway-secret
  flyway:
    enabled: true
    locations: "classpath:migrations"
    url: jdbc:mariadb://localhost:3306/gateway-database
    user: gateway
    password: gateway-secret
  cloud:
    gateway:
      enabled: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods:
              - POST
              - GET
              - DELETE
#      routes:
#        - id: service-a
#          uri: http://localhost:8082
#          predicates:
#            - Path=/aservice/**
#          filters:
#            - RewritePath=/aservice/(?<path>.*), /$\{path}

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "gateway"