
CREATE TABLE APP_ROUTE_DEFINITION (
    ID VARCHAR(255) PRIMARY KEY,
    URI VARCHAR(255) NOT NULL
);

CREATE TABLE APP_PREDICATE (
    ROUTE_ID VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    ARGS TEXT NOT NULL,
    PRIMARY KEY (ROUTE_ID, NAME),
    FOREIGN KEY (ROUTE_ID) REFERENCES APP_ROUTE_DEFINITION(ID)
);